--------------------------------------------------------
--  File created - Monday-January-01-2018   
--------------------------------------------------------
DROP SEQUENCE "DEVELOPER"."SHOP_ITEM_SEQ";
DROP SEQUENCE "DEVELOPER"."SHOP_LIST_SEQ";
DROP SEQUENCE "DEVELOPER"."SHOP_MANUFACTURER_SEQ";
DROP SEQUENCE "DEVELOPER"."SHOP_SECTION_MANUFACTURERS_SEQ";
DROP SEQUENCE "DEVELOPER"."SHOP_SECTION_SEQ";
DROP TABLE "DEVELOPER"."SHOP_ITEMS" cascade constraints;
DROP TABLE "DEVELOPER"."SHOP_LIST" cascade constraints;
DROP TABLE "DEVELOPER"."SHOP_MANUFACTURER" cascade constraints;
DROP TABLE "DEVELOPER"."SHOP_SECTIONS" cascade constraints;
DROP TABLE "DEVELOPER"."SHOP_SECTION_MANUFACTURERS" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence SHOP_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEVELOPER"."SHOP_ITEM_SEQ"  MINVALUE 1000 MAXVALUE 999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SHOP_LIST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEVELOPER"."SHOP_LIST_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SHOP_MANUFACTURER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEVELOPER"."SHOP_MANUFACTURER_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SHOP_SECTION_MANUFACTURERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEVELOPER"."SHOP_SECTION_MANUFACTURERS_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SHOP_SECTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEVELOPER"."SHOP_SECTION_SEQ"  MINVALUE 100 MAXVALUE 9999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table SHOP_ITEMS
--------------------------------------------------------

  CREATE TABLE "DEVELOPER"."SHOP_ITEMS" 
   (	"SHOP_ITEM_ID" NUMBER(10,0), 
	"SHOP_ITEM_NAME" VARCHAR2(30 BYTE), 
	"SHOP_ITEM_DESC" VARCHAR2(50 BYTE) DEFAULT 'No Description Available', 
	"SHOP_ITEM_SECTION_ID" NUMBER(10,0) DEFAULT 9999
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE" ;
--------------------------------------------------------
--  DDL for Table SHOP_LIST
--------------------------------------------------------

  CREATE TABLE "DEVELOPER"."SHOP_LIST" 
   (	"SHOP_LIST_ID" NUMBER(10,0), 
	"SHOP_LIST_NAME" VARCHAR2(30 BYTE), 
	"SHOP_LIST_TIMESTAMP" DATE DEFAULT SYSDATE, 
	"SHOP_LIST_DATA" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE" 
 LOB ("SHOP_LIST_DATA") STORE AS BASICFILE (
  TABLESPACE "DEV_SPACE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SHOP_MANUFACTURER
--------------------------------------------------------

  CREATE TABLE "DEVELOPER"."SHOP_MANUFACTURER" 
   (	"SHOP_MANUFACTURER_ID" NUMBER(10,0), 
	"SHOP_MANUFACTURER_NAME" VARCHAR2(20 BYTE), 
	"SHOP_MANUFACTURER_FULLNAME" VARCHAR2(50 BYTE), 
	"SHOP_MANUFACTURER_DESC" VARCHAR2(50 BYTE) DEFAULT 'No Description Available', 
	"SHOP_MANUFACTURER_LOGO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE" 
 LOB ("SHOP_MANUFACTURER_LOGO") STORE AS BASICFILE (
  TABLESPACE "DEV_SPACE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SHOP_SECTIONS
--------------------------------------------------------

  CREATE TABLE "DEVELOPER"."SHOP_SECTIONS" 
   (	"SHOP_SECTION_ID" NUMBER(10,0), 
	"SHOP_SECTION_NAME" VARCHAR2(30 BYTE), 
	"SHOP_SECTION_DESC" VARCHAR2(50 BYTE) DEFAULT 'No Description Available'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE" ;
--------------------------------------------------------
--  DDL for Table SHOP_SECTION_MANUFACTURERS
--------------------------------------------------------

  CREATE TABLE "DEVELOPER"."SHOP_SECTION_MANUFACTURERS" 
   (	"SHOP_SECTION_MANUFACTURER_ID" NUMBER(10,0), 
	"SHOP_MANUFACTURER_ID" NUMBER(10,0) DEFAULT 99999, 
	"SHOP_SECTION_ID" NUMBER(10,0) DEFAULT 9999
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE" ;
REM INSERTING into DEVELOPER.SHOP_ITEMS
SET DEFINE OFF;
REM INSERTING into DEVELOPER.SHOP_LIST
SET DEFINE OFF;
REM INSERTING into DEVELOPER.SHOP_MANUFACTURER
SET DEFINE OFF;
Insert into DEVELOPER.SHOP_MANUFACTURER (SHOP_MANUFACTURER_ID,SHOP_MANUFACTURER_NAME,SHOP_MANUFACTURER_FULLNAME,SHOP_MANUFACTURER_DESC) values (999999,'Generic','Generic Made','Generic');
REM INSERTING into DEVELOPER.SHOP_SECTIONS
SET DEFINE OFF;
Insert into DEVELOPER.SHOP_SECTIONS (SHOP_SECTION_ID,SHOP_SECTION_NAME,SHOP_SECTION_DESC) values (9999,'Miscellaneous','Miscellaneous Section');
REM INSERTING into DEVELOPER.SHOP_SECTION_MANUFACTURERS
SET DEFINE OFF;
Insert into DEVELOPER.SHOP_SECTION_MANUFACTURERS (SHOP_SECTION_MANUFACTURER_ID,SHOP_MANUFACTURER_ID,SHOP_SECTION_ID) values (99999999,999999,9999);
--------------------------------------------------------
--  DDL for Index SHOP_MANUFACTURER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVELOPER"."SHOP_MANUFACTURER_PK" ON "DEVELOPER"."SHOP_MANUFACTURER" ("SHOP_MANUFACTURER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE" ;
--------------------------------------------------------
--  DDL for Index SHOP_MANUFACTURER_SECTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVELOPER"."SHOP_MANUFACTURER_SECTIONS_PK" ON "DEVELOPER"."SHOP_SECTION_MANUFACTURERS" ("SHOP_SECTION_MANUFACTURER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE" ;
--------------------------------------------------------
--  DDL for Index SHOP_ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVELOPER"."SHOP_ITEMS_PK" ON "DEVELOPER"."SHOP_ITEMS" ("SHOP_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE" ;
--------------------------------------------------------
--  DDL for Index SHOP_SECTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVELOPER"."SHOP_SECTIONS_PK" ON "DEVELOPER"."SHOP_SECTIONS" ("SHOP_SECTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE" ;
--------------------------------------------------------
--  DDL for Index SHOP_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVELOPER"."SHOP_LIST_PK" ON "DEVELOPER"."SHOP_LIST" ("SHOP_LIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE" ;
--------------------------------------------------------
--  Constraints for Table SHOP_SECTIONS
--------------------------------------------------------

  ALTER TABLE "DEVELOPER"."SHOP_SECTIONS" ADD CONSTRAINT "SHOP_SECTIONS_PK" PRIMARY KEY ("SHOP_SECTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE"  ENABLE;
  ALTER TABLE "DEVELOPER"."SHOP_SECTIONS" MODIFY ("SHOP_SECTION_NAME" NOT NULL ENABLE);
  ALTER TABLE "DEVELOPER"."SHOP_SECTIONS" MODIFY ("SHOP_SECTION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOP_ITEMS
--------------------------------------------------------

  ALTER TABLE "DEVELOPER"."SHOP_ITEMS" MODIFY ("SHOP_ITEM_SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "DEVELOPER"."SHOP_ITEMS" ADD CONSTRAINT "SHOP_ITEMS_PK" PRIMARY KEY ("SHOP_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE"  ENABLE;
  ALTER TABLE "DEVELOPER"."SHOP_ITEMS" MODIFY ("SHOP_ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "DEVELOPER"."SHOP_ITEMS" MODIFY ("SHOP_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOP_LIST
--------------------------------------------------------

  ALTER TABLE "DEVELOPER"."SHOP_LIST" ADD CONSTRAINT "SHOP_LIST_PK" PRIMARY KEY ("SHOP_LIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE"  ENABLE;
  ALTER TABLE "DEVELOPER"."SHOP_LIST" MODIFY ("SHOP_LIST_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "DEVELOPER"."SHOP_LIST" MODIFY ("SHOP_LIST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOP_MANUFACTURER
--------------------------------------------------------

  ALTER TABLE "DEVELOPER"."SHOP_MANUFACTURER" ADD CONSTRAINT "SHOP_MANUFACTURER_PK" PRIMARY KEY ("SHOP_MANUFACTURER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE"  ENABLE;
  ALTER TABLE "DEVELOPER"."SHOP_MANUFACTURER" MODIFY ("SHOP_MANUFACTURER_FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "DEVELOPER"."SHOP_MANUFACTURER" MODIFY ("SHOP_MANUFACTURER_NAME" NOT NULL ENABLE);
  ALTER TABLE "DEVELOPER"."SHOP_MANUFACTURER" MODIFY ("SHOP_MANUFACTURER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOP_SECTION_MANUFACTURERS
--------------------------------------------------------

  ALTER TABLE "DEVELOPER"."SHOP_SECTION_MANUFACTURERS" ADD CONSTRAINT "SHOP_MANUFACTURER_SECTIONS_PK" PRIMARY KEY ("SHOP_SECTION_MANUFACTURER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV_SPACE"  ENABLE;
  ALTER TABLE "DEVELOPER"."SHOP_SECTION_MANUFACTURERS" MODIFY ("SHOP_SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "DEVELOPER"."SHOP_SECTION_MANUFACTURERS" MODIFY ("SHOP_MANUFACTURER_ID" NOT NULL ENABLE);
  ALTER TABLE "DEVELOPER"."SHOP_SECTION_MANUFACTURERS" MODIFY ("SHOP_SECTION_MANUFACTURER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SHOP_ITEMS
--------------------------------------------------------

  ALTER TABLE "DEVELOPER"."SHOP_ITEMS" ADD CONSTRAINT "SHOP_ITEMS_FK1" FOREIGN KEY ("SHOP_ITEM_SECTION_ID")
	  REFERENCES "DEVELOPER"."SHOP_SECTIONS" ("SHOP_SECTION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOP_SECTION_MANUFACTURERS
--------------------------------------------------------

  ALTER TABLE "DEVELOPER"."SHOP_SECTION_MANUFACTURERS" ADD CONSTRAINT "SHOP_SECTION_MANUFACTURER_FK1" FOREIGN KEY ("SHOP_MANUFACTURER_ID")
	  REFERENCES "DEVELOPER"."SHOP_MANUFACTURER" ("SHOP_MANUFACTURER_ID") ENABLE;
  ALTER TABLE "DEVELOPER"."SHOP_SECTION_MANUFACTURERS" ADD CONSTRAINT "SHOP_SECTION_MANUFACTURER_FK2" FOREIGN KEY ("SHOP_SECTION_ID")
	  REFERENCES "DEVELOPER"."SHOP_SECTIONS" ("SHOP_SECTION_ID") ENABLE;
