CREATE TABLESPACE dev_space DATAFILE 'dev_space.dat' SIZE 10M AUTOEXTEND ON;
CREATE USER developer IDENTIFIED BY developer DEFAULT TABLESPACE dev_space QUOTA UNLIMITED on dev_space;
GRANT CONNECT, RESOURCE TO DEVELOPER;